name: CI

on:
  push:
  pull_request:

permissions:
  contents: read

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v7

      - name: Set up .NET
        uses: actions/setup-dotnet@v6
        with:
          dotnet-version: 10.0.x

      - name: Restore
        run: dotnet restore EnvimixControl/EnvimixControl.csproj

      - name: Build
        run: dotnet build EnvimixControl/EnvimixControl.csproj --no-restore
